import Head from "next/head";
import Script from "next/script";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillMail,
} from "react-icons/ai";
import Typewriter from "typewriter-effect";
import { motion } from "framer-motion";
import { useState } from "react";

// Import JSON Data
import educationData from "../Data/educationData.json";
import experienceData from "../Data/experienceData.json";
import projectsData from "../Data/projectsData.json";
import recommendations from "../Data/recommendationData.json";
import skillsData from "../Data/skillsData.json";
import CustomCursor from "../Components/CustomCursor";
import BackToTopButton from "../Components/BackToTopButton";

export default function Home() {
  const [index, setIndex] = useState(0);

  const nextRecommendation = () => {
    setIndex((prevIndex) => (prevIndex + 1) % recommendations.length);
  };

  const prevRecommendation = () => {
    setIndex(
      (prevIndex) =>
        (prevIndex - 1 + recommendations.length) % recommendations.length
    );
  };

  // Scroll Animation Variants
  const sectionVariants = {
    hidden: { opacity: 0, y: 50 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 1, ease: "easeInOut" },
    },
  };

  return (
    <div>
      <CustomCursor/>
      <Head>
        <title>Jaydipsinh Padhiyar</title>
        <meta
          charSet="UTF-8"
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script
        src="//cdn.jsdelivr.net/github-cards/latest/widget.js"
        strategy="lazyOnload"
      />
      <Script
        src="https://www.twilik.com/assets/retainable/rss-embed/retainable-rss-embed.js"
        strategy="lazyOnload"
      />
      <Script
        src="https://unpkg.com/@rocktimsaikia/github-card@latest?module"
        strategy="lazyOnload"
      />

      <main className="bg-slate-50 px-4 md:px-10 dark:bg-slate-800">
        {/* Hero Section */}
        <section className="min-h-screen border-b-2 border-dashed border-orange-400">
          <motion.div
            initial="hidden"
            whileInView="visible"
            variants={sectionVariants}
            className="flex flex-col md:flex-row p-6 md:p-10 items-center"
          >
            {/* Left Side - Text */}
            <div className="flex-1 text-center md:text-left">
              <div className="p-6">
                <h2 className="text-4xl md:text-5xl py-2 text-orange-500 font-medium">
                  <Typewriter
                    options={{ autoStart: true, loop: true }}
                    onInit={(typewriter) => {
                      typewriter
                        .typeString("Hi There!")
                        .pauseFor(1000)
                        .deleteAll()
                        .typeString("I am Jaydipsinh Padhiyar.")
                        .start();
                    }}
                  />
                </h2>
                <div className="text-3xl flex justify-center md:justify-start space-x-4 py-2">
                  <span>🙏</span>
                  <span>💻</span>
                  <span>😎</span>
                </div>
                <h3 className="text-2xl py-2 dark:text-slate-50">
                  Full-Stack Developer, Tech Enthusiast, Programmer, and
                  Self-Learner.
                </h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-slate-100">
                  Passionate Full-Stack Developer and Tech Enthusiast pursuing a Master of Applied Computer Science at Dalhousie University, specializing in cloud and DevOps technologies.
                </p>
              </div>

              <div className="text-5xl flex justify-center md:justify-start gap-16 py-3 text-gray-600 dark:text-gray-300">
                <a href="https://twitter.com/jpsinh27">
                  <AiFillTwitterCircle className="hover:text-black" />
                </a>
                <a href="https://www.linkedin.com/in/jaydipsinh-padhiyar/">
                  <AiFillLinkedin className="hover:text-black" />
                </a>
                <a href="mailto:jaydipadhiyar27@gmail.com">
                  <AiFillMail className="hover:text-black" />
                </a>
              </div>
            </div>


            {/* Right Side - Image */}
            <div className="flex-1 flex justify-center items-center p-6 md:p-10">
              <motion.img
                src="/Logo.png"
                alt="Jaydipsinh Padhiyar"
                className="rounded-full shadow-lg w-80 h-90 md:w-80 md:h-90 object-cover border-4 border-orange-500"
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 1, ease: "easeInOut" }}
              />
            </div>
          </motion.div>
        </section>

        {/* Skills Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          variants={sectionVariants}
          className="min-h-screen border-b-2 border-dashed border-orange-400 mb-10"
        >
          <div className="text-center shadow-lg p-6 md:p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm">
            <h3 className="text-3xl py-1 font-medium font-mono">🛠️ Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              Here are a few of the skills I bring to the table.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-5 border-l-2 border-r-2 border-t-2 mb-10 border-dashed p-6 md:p-10 shadow-md dark:text-slate-50">
            {skillsData.skills.map((skill, idx) => (
              <motion.div
                key={idx}
                whileHover={{ scale: 1.05 }}
                className="text-center shadow-lg p-6 md:p-10 rounded-xl my-6 dark:shadow-slate-300 dark:shadow-sm"
              >
                <h3 className="text-lg font-medium pt-8 pb-2 ">
                  {skill.category}
                </h3>
                <p className="py-2">{skill.details}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* Education Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          variants={sectionVariants}
          className="min-h-screen border-b-2 border-dashed border-orange-400"
        >
          <div className="text-center shadow-lg p-6 md:p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm">
            <h3 className="text-3xl py-1 font-medium font-mono">
              🎓 Education
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              Here is my education background:
            </p>

            <div className="text-left mt-6 ml-4">
              {educationData.map((edu, idx) => (
                <div key={idx} className="mb-6">
                  <p className="text-lg">
                    {edu.institution} ({edu.year})
                  </p>
                  <p>
                    {edu.degree} | GPA: {edu.gpa}
                  </p>
                  {edu.courses && (
                    <ul className="list-disc ml-6">
                      {edu.courses.map((course, courseIdx) => (
                        <li key={courseIdx} className="text-sm py-1">
                          {course}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </div>
        </motion.section>

        {/* Experience Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          variants={sectionVariants}
          className="min-h-screen border-b-2 border-dashed border-orange-400"
        >
          <div className="text-center shadow-lg p-6 md:p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm">
            <h3 className="text-3xl py-1 font-medium font-mono">
              💼 Experience
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              Here's my work experience:
            </p>

            <div className="text-left mt-6 ml-4">
              {experienceData.map((exp, idx) => (
                <div key={idx} className="mb-6">
                  <p className="text-lg">
                    {exp.company} ({exp.period})
                  </p>
                  <p>{exp.role}:</p>
                  <ul className="list-disc ml-6">
                    {exp.details.map((detail, detailIdx) => (
                      <li key={detailIdx} className="text-sm py-1">
                        {detail}
                      </li>
                    ))}
                  </ul>
                  {exp.certificateLink && (
                    <a
                      href={exp.certificateLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-orange-500 hover:underline"
                    >
                      View Certificate
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>
        </motion.section>

        {/* Projects Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          variants={sectionVariants}
          className="min-h-screen border-b-2 border-dashed border-orange-400"
        >
          <div className="text-center shadow-lg p-6 md:p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm">
            <h3 className="text-3xl py-1 font-medium font-mono">💻 Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              Here are some of the projects I've worked on:
            </p>

            <div className="text-left mt-6 ml-4">
              {projectsData.map((proj, idx) => (
                <div key={idx} className="mb-6">
                  <p className="text-lg">
                    {proj.title} ({proj.stack})
                  </p>
                  <ul className="list-disc ml-6">
                    {proj.details.map((detail, detailIdx) => (
                      <li key={detailIdx} className="text-sm py-1">
                        {detail}
                      </li>
                    ))}
                  </ul>
                  {proj.githubLink && (
                    <a
                      href={proj.githubLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-orange-500 hover:underline"
                    >
                      View on GitHub
                    </a>
                  )}
                </div>
              ))}
            </div>
          </div>
        </motion.section>
        

        {/* What Others Say About Me Section */}
        <motion.section
          initial="hidden"
          whileInView="visible"
          variants={sectionVariants}
          className="min-h-screen border-b-2 border-dashed border-orange-400"
        >
          <div className="text-center shadow-lg p-6 md:p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm">
            <h3 className="text-3xl py-1 font-medium font-mono text-gray-900 dark:text-white">
              💬 What Others Say About Me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-100 font-medium">
              Here's what people are saying:
            </p>

            {/* Framer Motion Card Swiper */}
            <motion.div
              key={index}
              initial={{ opacity: 0, x: 100 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -100 }}
              transition={{ duration: 0.8 }}
              className="text-center bg-white dark:bg-gray-800 p-6 shadow-md rounded-lg mt-6 max-w-xl mx-auto"
            >
              <blockquote className="text-lg font-medium text-gray-700 dark:text-gray-200 italic">
                "{recommendations[index].text}"
              </blockquote>
              <p className="text-md font-semibold text-gray-600 dark:text-gray-400 mt-4">
                - {recommendations[index].name}, {recommendations[index].title}
              </p>
            </motion.div>

            {/* Navigation Buttons */}
            <div className="flex justify-center mt-4 gap-4">
              <button
                onClick={prevRecommendation}
                className="bg-orange-500 text-white font-medium px-4 py-2 rounded-full shadow-md hover:bg-orange-600 transition duration-200"
              >
                ⬅️ Previous
              </button>
              <button
                onClick={nextRecommendation}
                className="bg-orange-500 text-white font-medium px-4 py-2 rounded-full shadow-md hover:bg-orange-600 transition duration-200"
              >
                Next ➡️
              </button>
            </div>
          </div>
        </motion.section>
        <BackToTopButton />
      </main>
    </div>
  );
}
