import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import Image from 'next/image'

import styles from '../styles/Home.module.css'

import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillMail } from 'react-icons/ai'
import Typewriter from "typewriter-effect"

import d31 from '../public/3d1.png'
// import avatar from '../public/avatar.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'


export default function Home() {



  return (
    <div>
      <Head>
        <title>Jaydipsinh Padhiyar</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta charSet='UTF-8' name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.png" />
        {/* <script src="//cdn.jsdelivr.net/github-cards/latest/widget.js"></script> */}
      </Head>

      <Script
        src="//cdn.jsdelivr.net/github-cards/latest/widget.js"
        strategy="lazyOnload"
      />
      <Script
        src="https://www.twilik.com/assets/retainable/rss-embed/retainable-rss-embed.js"
        strategy="lazyOnload"
      />
      <Script
        src="https://unpkg.com/@rocktimsaikia/github-card@latest?module"
        strategy="lazyOnload"
      />

      <main className="bg-slate-50 px-10 dark:bg-slate-800">
        <section className="min-h-screen border-b-2 border-dashed border-orange-400">

          <div className='flex p-10 max-lg:flex-col max-lg:items-center '>
            <div>

              <div className="text-center p-10 ">


                <h2 className="text-5xl py-2 text-orange-500 font-medium">
                  <Typewriter
                    options={{
                      autoStart: true,
                      loop: true,
                    }}
                    onInit={(typewriter) => {

                      typewriter

                        .typeString("Namaste!")

                        .pauseFor(1000)
                        .deleteAll()
                        .typeString("I am Jaydipsinh Padhiyar.")
                        .start()
                        .pauseFor(2000);

                    }}
                  />
                </h2>
                <span className='text-3xl'>&#128591;</span>
                <span className='text-3xl'>&#128187;</span>
                <span className='text-3xl'>&#128526;</span>
                <h3 className="text-2xl py-2 dark:text-slate-50">Full-Stack Developer, Tech Enthusiast, Programmer, and Self-Learner.</h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-slate-100"> Freelancer providing services for programming and design content needs. Join me down below and let&apos;s get cracking!</p>
              </div>

              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
                <a href="https://twitter.com/jpsinh27"><AiFillTwitterCircle className="hover:text-black" /></a>
                <a href="https://www.linkedin.com/in/jaydipsinh-padhiyar/"><AiFillLinkedin className="hover:text-black" /></a>
                {/* <a href="https://github.com/JAYDIPSINH27"><AiFillGithub className="hover:text-black" /></a> */}
                <a href="mailto:jaydipadhiyar27@gmail.com"><AiFillMail className="hover:text-black" /></a>

              </div>
            </div>

            <div className="relative mt-10 bg-gradient-to-b from-yellow-300 rounded-full w-80 h-80 max-lg:overflow-hidden">
              <Image src={d31} className="" alt="Hero Image" />
            </div>

          </div>
        </section>

        {/* Second Page */}

        <section className='min-h-screen border-b-2 border-dashed border-orange-400 mb-10 '>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm'>
            <h3 className="text-3xl py-1 font-medium font-mono ">Services I offer</h3>
            <p className="text-md py-2 leading-8 font-medium">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-orange-500"> agencies </span>
              consulted for <span className="text-orange-500">startups </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>


          <div className='flex gap-6 max-lg:flex-col border-l-2 border-r-2 border-t-2 mb-10 border-dashed p-10 shadow-md  dark:text-slate-50'>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:shadow-slate-300 dark:shadow-sm'>
              <Image src={design} alt="Design Image" className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core
                design theory.
              </p>

            </div>



            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:shadow-slate-300 dark:shadow-sm '>
              <Image src={code} alt="Code Image" className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Code your dream project</h3>
              <p className='py-2'> Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>

            </div>



            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:shadow-slate-300 dark:shadow-sm'>
              <Image src={consulting} alt="Consulting Image" className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Consulting</h3>
              <p className='py-2'> Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>

            </div>

          </div>
        </section>

        {/* Section 3 */}
        <section className='min-h-screen border-b-2 border-dashed border-orange-400'>
          <div className='text-center shadow-lg p-10 rounded-xl my-5 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm'>
            <h3 className="text-3xl py-1 font-medium font-mono ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              Here are a few of the projects I&apos;ve worked on. Please see my <span className="text-orange-500">Github</span> repositories.
              If you wish to add additional features, you can get in touch with me and fork my repository.

            </p>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              I do Open Source Contributions on Github.
            </p>
          </div>

          <div className="flex justify-center gap-16 py-3 text-gray-600">
            {/* <div class="github-card" data-github="JAYDIPSINH27" data-width="400" data-height="" data-theme="medium" data-target="blank"></div> */}
            {/* <a href="https://github.com/"><img src="https://gh-card.dev/repos/.svg" /></a> */}
            <github-card data-user="JAYDIPSINH27" data-theme="dark"></github-card>
          </div>

          <div className="flex mb-10 shadow-md justify-center flex-row gap-10 py-10 max-lg:shadow-none max-lg:flex-col max-lg:items-center max-lg:p-20 max-lg:mx-20 max-lg:border-none border-l-2 border-r-2 border-t-2 border-dashed">

            <div className="github-card" data-github="JAYDIPSINH27/FurrEverHome" data-width="400" data-height="356" data-theme="medium"></div>
            <div className="github-card" data-github="JAYDIPSINH27/spider-bug-tracker" data-width="400" data-height="" data-theme="medium"></div>
            <div className="github-card" data-github="JAYDIPSINH27/TextEdit" data-width="400" data-height="337" data-theme="medium"></div>

          </div>

        </section>

        {/* Section 4 */}
        <section className='min-h-screen border-b-2 border-dashed border-orange-400 '>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-row bg-[#B9E0FF] dark:bg-[#21E6C1] bg-opacity-70 backdrop-blur-3xl dark:shadow-slate-300 dark:shadow-sm'>
            <h3 className="text-3xl py-1 font-medium font-mono">Blog</h3>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              I frequently post new articles to <span className="text-orange-500">Medium</span>. Please <span className="text-orange-500">follow me </span> to receive new, up-to-date technology-related blogs and information.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 font-medium">
              I Give insights on wider range of topics from Latest Technologies to New frameworks and Beginner Tutorials.
            </p>
          </div>

          <div className='border-l-2 mb-10 border-r-2 border-t-2  border-dashed shadow-md p-10 rounded-xl my-10 '>
            <div className="border-4 shadow-lg p-10 rounded-xl my-10" id="retainable-rss-embed"
              data-rss="https://medium.com/feed/@jaydipadhiyar27"
              data-maxcols="2"
              data-layout="slider"
              data-poststyle="external"
              // data-readmore="Read the rest"
              data-buttonclass="btn btn-dark"
              data-offset="-100">
            </div>
          </div>

        </section>
      </main>
    </div>
  )
}
