import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import Image from 'next/image'

import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillMail } from 'react-icons/ai'
import Typewriter from "typewriter-effect"

import d31 from '../public/3d1.png'
// import avatar from '../public/avatar.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jaydipsinh Padhiyar</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta charSet='UTF-8' name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.png" />
        {/* <script src="//cdn.jsdelivr.net/github-cards/latest/widget.js"></script> */}
      </Head>

      {/* <Script
        src="//cdn.jsdelivr.net/github-cards/latest/widget.js"
        strategy="lazyOnload"
      /> */}
      <Script
        src="https://www.twilik.com/assets/retainable/rss-embed/retainable-rss-embed.js"
        strategy="lazyOnload"
      />
      <Script
        src="https://unpkg.com/@rocktimsaikia/github-card@latest?module"
        strategy="lazyOnload"
      />

      <main className="bg-slate-50 px-10 ">
        <section className="min-h-screen divide-yellow-200 divide-dashed">
          {/* {<nav className='py-5 mb-12 flex justify-between border-b-2'> */}

            {/* <h1 className='text-xl font-burtons font-semibold hover:text-orange-500'><Link href="/" >Jaydipsinh Padhiyar</Link></h1> */}
            {/* <ul className=" flex items-center"> */}
              {/* <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl" /></li> */}
              {/* Without Gradient */}
              {/* <li><a className="bg-cyan-500 text-white px-4 py-2  rounded-md ml-8" href="#">Resume</a></li> */}
              {/* <li><a href="https://drive.google.com/file/d/1LsjXNVjN0uTOUAyn7cClrRr4LjIkBbOG/view?usp=share_link" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2  rounded-md ml-8">Resume</a></li> */}
            {/* </ul> */}
          {/* </nav> */}

          <div className='flex p-10 max-lg:flex-col max-lg:items-center'>
            <div>

              <div className="text-center p-10">


                <h2 className="text-5xl py-2 text-orange-500 font-medium">
                  <Typewriter
                    options={{
                      autoStart: true,
                      loop: true,
                    }}
                    onInit={(typewriter) => {

                      typewriter

                        .typeString("Namaste!")

                        .pauseFor(1000)
                        .deleteAll()
                        .typeString("I am Jaydipsinh Padhiyar.")
                        .start()
                        .pauseFor(2000);

                    }}
                  />
                </h2>
                <span className='text-3xl'>&#128591;</span>
                <span className='text-3xl'>&#128187;</span>
                <span className='text-3xl'>&#128526;</span>
                <h3 className="text-2xl py-2">Full-Stack Developer, Tech Enthusiast, Programmer, and Self-Learner.</h3>
                <p className="text-md py-5 leading-8 text-gray-800"> Freelancer providing services for programming and design content needs. Join me down below and let's get cracking!</p>
              </div>

              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                <a href="https://twitter.com/jpsinh27"><AiFillTwitterCircle className="hover:text-black" /></a>
                <a href="https://www.linkedin.com/in/jaydipsinh-padhiyar/"><AiFillLinkedin className="hover:text-black" /></a>
                {/* <a href="https://github.com/JAYDIPSINH27"><AiFillGithub className="hover:text-black" /></a> */}
                <a href="mailto:jaydipadhiyar27@gmail.com"><AiFillMail className="hover:text-black" /></a>
                
              </div>
            </div>

            <div className="relative mt-10 bg-gradient-to-b from-yellow-300 rounded-full w-80 h-80 max-lg:overflow-hidden">
              <Image src={d31} className="" />
            </div>

          </div>
        </section>

        {/* Second Page */}

        <section className='min-h-screen'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-row'>
            <h3 className="text-3xl py-1 ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 ">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className="flex justify-center gap-16 py-3 text-gray-600">
                {/* <div class="github-card" data-github="JAYDIPSINH27" data-width="400" data-height="" data-theme="medium" data-target="blank"></div> */}
                {/* <a href="https://github.com/"><img src="https://gh-card.dev/repos/.svg" /></a> */}
                <github-card data-user="JAYDIPSINH27" data-theme="dark"></github-card>
              </div>

          <div className='flex gap-6 max-lg:flex-col'>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={design} className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>



            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={code} className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Code your dream project</h3>
              <p className='py-2'> Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>



            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={consulting} className="mx-auto" width={100} hight={100} />
              <h3 className='text-lg font-medium pt-8 pb-2 '>Consulting</h3>
              <p className='py-2'> Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className='py-4 text-teal-600'>Design Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

          </div>
        </section>

        {/* Section 3 */}
        <section className='min-h-screen'>
          <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-row'>
            <h3 className="text-3xl py-1 ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 ">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className='shadow-lg p-10 rounded-xl my-10'>
          <div className="border-4 shadow-lg p-10 rounded-xl my-10" id="retainable-rss-embed"
            data-rss="https://medium.com/feed/retainable,https://medium.com/feed/@jaydipadhiyar27"
            data-maxcols="2"
            data-layout="slider"
            data-poststyle="external"
            // data-readmore="Read the rest"
            data-buttonclass="btn btn-dark"
            data-offset="-100">
            </div>
            </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>

        </section>
      </main>
    </div>
  )
}
